#!/bin/bash
echo -------------------------------------------
echo    Flashen eines seriellen Bootloaders
echo    fuer einen ATmega8 mit 38400 Baud und
echo    internem 8 MHz Takt
echo
echo    03.01.2021 R. Seelig
echo  -------------------------------------------

ch340reset
avrdude -c stk500v2 -p m8 -P /dev/ttyUSB0 -b 115200 -B 10 -U lfuse:w:0xd4:m -U hfuse:w:0xca:m
ch340reset
avrdude -c stk500v2 -p m8 -P /dev/ttyUSB0 -b 115200 -B 5 -U flash:w:boot_atmega8_8mhz_38400bd.hex
